### ISSUE TITLE
Make $ non selectable in commands

### ISSUE THREAD

**Issue by superbonaci** [darlinghq/darling-docs#29]
All doc pages, example https://docs.darlinghq.org/contributing/generating-stubs.html
There are commands:
````
$ mkdir ~/bin
````
Either you double-click to select all line, or hit the copy floating icon, it copies the command as well the dollar symbol plus space `$ ` (or `% `).
This could be fixed making those 2 characters non-selectable for all commands.

Example URL: https://css-tricks.com/to-or-not-to-displaying-terminal-code-snippets/
Example code on that URL: `brew install buttnugget` (notice doesn't select `$ `).
[brew.sh](https://brew.sh/) homepage itself does this.

**Comment by CuriousTommy** [comment]
Closing as PR #56 has been merge (it's more easier to just get rid of the `$`)
