### ISSUE TITLE
Improve explanation about Generating stubs section

### ISSUE THREAD

**Issue by superbonaci** [darlinghq/darling-docs#30]
Top section `Generating stubs` (https://docs.darlinghq.org/contributing/generating-stubs.html)

Says "A computer running macOS is required to run the stub generator."
It should clear out, that all below commands are meant to be run from within a running OS X itself, not mounting the root OS X volume under Linux (which probably can be done but commands will be other).

**Comment by hamishmb** [comment]
If you read the section at the bottom (Known Issues) it is mentioned that it doesn't work if not running macOS or iOS - this seems redundant.

**Comment by CuriousTommy** [comment]
IMO, "A computer running macOS" implies that you need to run the tool on macOS. If that wasn't required, the instruction would of said "The tool requires a copy of a macOS install to generate the stubs", or something along those lines.

I'm going close this issue.
