### ISSUE TITLE
Add instructions about how to shutdown darling

### ISSUE THREAD

**Issue by superbonaci** [darlinghq/darling-docs#33]
I'm trying to unload darling kernel module, but no idea why doesn't work:
````
sudo rmmod darling_mach 
rmmod: ERROR: Module darling_mach is in use
````
Could be possible to add to guide how to perform such operation?

**Comment by LubosD** [comment]
Please stop opening so many issues... The kernel module cannot be unloaded so long as you have any macOS processes running.

**Comment by superbonaci** [comment]
I `exit` from darling shell, how to I stop macOS processes? How do I detect which ones are, without having to reboot to unload them?

**Comment by superbonaci** [comment]
It can be done with this:
````
sudo killall -9 mach_thread_cal darling-foreign launchd launchctl shellspawn syslogd iokitd memberd securityd notifyd aslmanager
sudo rmmod darling_mach
````
