### ISSUE TITLE
copy button copies the dollar

### ISSUE THREAD

**Issue by superbonaci** [darlinghq/darling-docs#36]
https://docs.darlinghq.org/build-instructions.html
Copy button after "If you have already cloned Darling and would like to get the latest changes, do this in the source root:" copies the dollars:
```
$ git pull
$ git submodule init
$ git submodule update
```
When it should copy
```
git pull
git submodule init
git submodule update
```

**Comment by CuriousTommy** [comment]
https://github.com/darlinghq/darling-docs/pull/56 has been merged, so I'll close this issue.
