### ISSUE TITLE
Ubuntu 21.10 instructions

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [darlinghq/darling-docs#37]
`libavresample-dev` isn't available for Ubuntu 21.10 for some reason.

**Comment by SIGSTACKFAULT** [comment]
![<facekapow> the real solution is that we need to update our code to use libswresample instead of libavresample, as the latter is deprecated and (as you already found out yourself) being phased out of software repos.](https://user-images.githubusercontent.com/14184826/149830222-3b44a572-715b-4907-9ecf-34cfdbcd81e1.png)

**Comment by facekapow** [comment]
Fixed, as we switched to libswresample a few months ago
