### ISSUE TITLE
Blog offline 

### ISSUE THREAD

**Issue by superbonaci** [darlinghq/darling-docs#58]
Times out when trying to load the blog:
http://blog.darlinghq.org/

**Comment by CuriousTommy** [comment]
Works fine on my end 
![Screenshot_20230117-090528](https://user-images.githubusercontent.com/3105794/212964822-5c0cbe08-2214-4aa0-b247-a10da309658d.png)

**Comment by superbonaci** [comment]
Maybe some temporary server issue.
